---
- hosts: all
  become: yes
  tasks:
  - name: Install packages
    apt:
      name:
      - ntpdate
      - nmap
      - htop
      - mc
      - cockpit
      state: latest
      cache_valid_time: 3600