---
- hosts: all
  become: yes
  become_method: enable
  tasks:
  - name: Install packages
    apt:
      name:
      - ntpdate
      - nmap
      - htop
      - mc
      - cockpit
      - links2
      state: latest
      cache_valid_time: 3600
