---
- hosts: all
  become: yes
  become_method: enable
  tasks:
    - name: Enable Root Login
     lineinfile:
           dest: /etc/ssh/sshd_config
           regexp: '^PermitRootLogin'
           line: "PermitRootLogin yes"
           state: present
           backup: yes
     become: yes
     notify:
       - restart ssh

   handlers:
   - name: restart ssh
     systemctl:
       name: sshd
       state: restarted
